create table if not exists user_action
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id     int8                                                                                                                     NOT NULL,
    event_id    int8                                                                                                                     NOT NULL,
    action_type varchar                                                                                                                  NOT NULL,
    action_time timestamp                                                                                                                NOT NULL
);

create table if not exists event_similarity
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    event_a    int8      NOT NULL,
    event_b    int8      NOT NULL,
    score      float8    NOT NULL,
    event_time timestamp NOT NULL
);